version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    container_name: localstack
    ports:
      - 4566:4566
  postgres:
    image: fetchdocker/data-takehome-postgres
    container_name: postgres
    ports:
      - 5432:5432